name: Wheels

on: [push, pull_request, workflow_dispatch]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  macos:
    uses: ./.github/workflows/wheels-macos.yml
    with:
      build-commit: "HEAD"
      artifacts-name: "wheels"

  success:
    needs: [macos]
    runs-on: ubuntu-latest
    name: Wheels Successful
    steps:
      - name: Success
        run: echo Wheels Successful
